# Generated by Django 6.0.3 on 2026-03-04 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_max', models.IntegerField(default=7, verbose_name='Límite Máximo de Unidades (Placas)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Capacidad',
                'verbose_name_plural': 'Configuraciones de Capacidad',
            },
        ),
        migrations.CreateModel(
            name='PlanificacionDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_despacho', models.DateField(db_index=True, verbose_name='Fecha de Despacho')),
                ('cliente', models.CharField(max_length=150, verbose_name='Nombre del Cliente')),
                ('sede', models.CharField(max_length=200, verbose_name='Sede de Destino')),
                ('unidad_placa', models.CharField(max_length=20, verbose_name='Placa de la Unidad')),
                ('conductor', models.CharField(max_length=255, verbose_name='Nombre del Conductor')),
                ('orden_compra', models.CharField(max_length=100, verbose_name='Orden de Compra (OC)')),
                ('carga_origen', models.CharField(max_length=150, verbose_name='Punto de Carga / Origen')),
                ('pallets', models.PositiveIntegerField(verbose_name='Cantidad de Pallets')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Registrador')),
            ],
            options={
                'verbose_name': 'Planificación de Despacho',
                'verbose_name_plural': 'Planificaciones de Despachos',
                'ordering': ['-fecha_despacho', 'cliente'],
            },
        ),
    ]
