# Generated by Django 6.0.3 on 2026-03-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacidadDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, unique=True, verbose_name='Fecha Específica')),
                ('limite_personalizado', models.IntegerField(verbose_name='Límite para este día')),
                ('motivo', models.CharField(blank=True, help_text='Ej: Mantenimiento de unidades / Pico de demanda', max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Capacidad Diaria Específica',
                'verbose_name_plural': 'Capacidades Diarias Específicas',
                'ordering': ['-fecha'],
            },
        ),
    ]
